import 'dart:convert';
import 'package:flutter/foundation.dart';
import '../models/prescription_model.dart';
import '../models/medicine_model.dart';

/// QR Sharing Service - Generate and share prescription data via QR codes
class QRSharingService {
  /// Generate QR data from prescription
  String generateQRData(PrescriptionModel prescription) {
    final data = {
      'id': prescription.id,
      'date': prescription.uploadedAt.toIso8601String(),
      'medicines': prescription.medicines.map((m) => {
        'name': m.name,
        'dosage': m.dosage,
        'timing': m.timing,
        'confidence': m.confidence,
      }).toList(),
      'language': prescription.language,
    };

    return jsonEncode(data);
  }

  /// Generate QR data from medicine list
  String generateQRDataFromMedicines(List<MedicineModel> medicines) {
    final data = {
      'type': 'medicine_list',
      'date': DateTime.now().toIso8601String(),
      'medicines': medicines.map((m) => {
        'name': m.name,
        'dosage': m.dosage,
        'timing': m.timing,
      }).toList(),
    };

    return jsonEncode(data);
  }

  /// Parse QR data to prescription info
  Map<String, dynamic>? parseQRData(String qrData) {
    try {
      final data = jsonDecode(qrData);
      return data;
    } catch (e) {
      debugPrint('Error parsing QR data: $e');
      return null;
    }
  }

  /// Generate shareable text from prescription
  String generateShareableText(PrescriptionModel prescription) {
    final buffer = StringBuffer();
    buffer.writeln('📋 MediSure Prescription');
    buffer.writeln('Date: ${_formatDate(prescription.uploadedAt)}');
    buffer.writeln('');
    buffer.writeln('💊 Medicines (${prescription.medicines.length}):');
    buffer.writeln('');

    for (var i = 0; i < prescription.medicines.length; i++) {
      final medicine = prescription.medicines[i];
      buffer.writeln('${i + 1}. ${medicine.name}');
      buffer.writeln('   Dosage: ${medicine.dosage}');
      buffer.writeln('   Timing: ${medicine.timing}');
      buffer.writeln('');
    }

    buffer.writeln('Generated by MediSure App');
    return buffer.toString();
  }

  /// Generate shareable text from single medicine
  String generateMedicineShareText(MedicineModel medicine) {
    return '''
💊 ${medicine.name}
📊 Dosage: ${medicine.dosage}
⏰ Timing: ${medicine.timing}
📝 Notes: ${medicine.notes}

Shared via MediSure App
''';
  }

  /// Generate emergency contact card data
  String generateEmergencyCardData({
    required String patientName,
    required String bloodGroup,
    required String emergencyContact,
    required List<String> allergies,
    required List<String> currentMedications,
  }) {
    final data = {
      'type': 'emergency_card',
      'patient': patientName,
      'bloodGroup': bloodGroup,
      'emergencyContact': emergencyContact,
      'allergies': allergies,
      'medications': currentMedications,
      'generated': DateTime.now().toIso8601String(),
    };

    return jsonEncode(data);
  }

  /// Format date for display
  String _formatDate(DateTime date) {
    return '${date.day}/${date.month}/${date.year} ${date.hour}:${date.minute.toString().padLeft(2, '0')}';
  }

  /// Validate QR data format
  bool isValidQRData(String qrData) {
    try {
      final data = jsonDecode(qrData);
      return data is Map && 
             (data.containsKey('medicines') || data.containsKey('type'));
    } catch (e) {
      return false;
    }
  }

  /// Get QR data size in bytes
  int getQRDataSize(String qrData) {
    return utf8.encode(qrData).length;
  }

  /// Check if QR data is too large (>2KB recommended for QR codes)
  bool isQRDataTooLarge(String qrData) {
    return getQRDataSize(qrData) > 2048;
  }

  /// Compress QR data by removing unnecessary fields
  String compressQRData(String qrData) {
    try {
      final data = jsonDecode(qrData);
      
      // Remove confidence scores and notes to reduce size
      if (data['medicines'] != null) {
        for (var medicine in data['medicines']) {
          medicine.remove('confidence');
          medicine.remove('notes');
        }
      }
      
      return jsonEncode(data);
    } catch (e) {
      return qrData;
    }
  }
}
